### ISSUE TITLE
make hubot able to deploy to staging

### ISSUE THREAD

**Issue by gfoster** [taskrabbit/hubot#1]
commands should be something like:

> <bot_name> deploy <project>/<branch> to staging #

example:

> hodor deploy v3/my_test_branch" to staging 4

This should do a git fetch/pull in the appropriate repo, then run ansible locally. Ansible command for the above looks like this:

> ansible-playbook -i inventories/staging deploy.yml –extra-vars=“application=v3 migrate=true branch=my_test_branch” –limit staging-4.taskrabbit.in

**Comment by gfoster** [comment]
repos should be stored in ~deploy/repos
optionally, check to see if a local copy of the repo exists and either clone it or update it as appropriate

**Comment by odlund** [comment]
It would be cool if deploy was aware of the reservation status of the server you are trying to deploy to, and either stop us from deploying or automagically reserving the server

**Comment by gfoster** [comment]
hubot now requires you to own the reservation to the server you are deploying to
